version = 0.1

[default.deploy.parameters]
stack_name = "staging-todo-list-aws"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Stage=staging TableName=todo-table-staging"
resolve_s3 = true
no_fail_on_empty_changeset = true


