version = 0.1

[default.deploy.parameters]
stack_name = "production-todo-list-aws"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Stage=production TableName=todo-table-production"
s3_bucket = "todo-list-aws-sam-bucket"
no_fail_on_empty_changeset = true
